/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerImp;
import java.io.IOException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

/**
 *
 * @author whiwf
 */
public class FormNhanVien extends javax.swing.JPanel 
                        implements View{

    private String fileName = "NV.TXT";
    private DefaultTableModel model;
    private List<NhanVien> listNV;
    private ControllerImp controller;
    
    public FormNhanVien() {
        initComponents();
        setSize(800, 600);
        String cols[] = {"Ma NV", "Ho ten", "Dia chi",
                        "SDT", "Bac luong"};
        model = new DefaultTableModel(cols, 0);
        jTable1.setModel(model);
        listNV = new ArrayList<>(); 
        controller = new ControllerImp();
        showFromFile(listNV, model, fileName);
        btnFalse();
    }
    
    private void btnFalse(){
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }

    private void btnTrue(){
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
    }
    
    private void clearData(){
        tfMa.setText("");
        tfTen.setText("");
        tfDiaChi.setText("");
        tfSDT.setText("");
    }

    public List getListNhanVien(){
        return listNV;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        tfDiaChi = new javax.swing.JTextField();
        tfSDT = new javax.swing.JTextField();
        cbBac = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfMa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ho ten:");

        jLabel2.setText("Dia chi:");

        jLabel3.setText("SDT:");

        jLabel4.setText("Bac luong:");

        cbBac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jButton2.setText("Luu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Ma NV");

        tfMa.setEditable(false);

        jButton3.setText("Huy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTen)
                            .addComponent(tfDiaChi)
                            .addComponent(tfSDT)
                            .addComponent(cbBac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbBac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btnTrue();
        clearData();
        String sMa = String.format("%04d", NhanVien.getsMa());
        tfMa.setText(sMa);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearData();
        btnFalse();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ten = "", diaChi = "", soDT = "";
        int bac = Integer.parseInt((String) cbBac.getSelectedItem());
        boolean isOk = true;
        
        //nhap ten
        try{
            ten = tfTen.getText().replaceAll("\\s+", " ").trim();
            if(ten.length() == 0){
                throw new IOException();
            }
            String rgTen = "^[a-zA-Z]+$";
            String checkTen[] = ten.split(" ");
            for(String check : checkTen){
                if(!check.matches(rgTen))
                    throw new InputMismatchException();
            }
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Ten khong duoc de trong");
            isOk = false;
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "Ten sai dinh dang");
            isOk = false;
        }
        //nhap dia chi
        try{
            diaChi = tfDiaChi.getText().replaceAll("\\s+", " ").trim();
            if(diaChi.length() == 0){
                throw new IOException();
            }
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Dia chi khong duoc de trong");
            isOk = false;
        } 
        //nhap so dien thoai
        try{
            soDT = tfSDT.getText().trim();
            if(soDT.length() == 0){
                throw new IOException();
            }
            String rgSo = "^[0-9]+$";
            if(!soDT.matches(rgSo))
                throw new InputMismatchException();
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "SDT khong duoc de trong");
            isOk = false;
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "SDT sai dinh dang");
            isOk = false;
        }
        
        if(isOk){
            NhanVien nv = new NhanVien(ten, diaChi, soDT, bac);
            addTo(nv);
            btnFalse();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfMa;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for(T nv: list){
            if(nv instanceof NhanVien){
                this.model.addRow(((NhanVien) nv).toObject());
            }
        }
    }

    @Override
    public <T> void addTo(T t) {
        listNV.add((NhanVien) t);
        showData(listNV, model);
        controller.writeToFile(fileName, listNV);
    }

    @Override
    public <T> void showFromFile(List<T> list, DefaultTableModel model, String fileName) {
        list = controller.readFromFile(fileName);
        if(list.size() > 0){
            listNV = (List<NhanVien>) list;
            int ma = listNV.get(listNV.size() - 1).getMaNV();
            NhanVien.setsMa(ma + 1);
        }
        showData(list, model);
    }
}
