/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDanhSachChamCong;
import model.NhanVien;
import model.PhongBan;

/**
 *
 * @author whiwf
 */
public class FormChamCong extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormChamCong
     */
    private DefaultTableModel model;
    private List<PhongBan> listPB;
    private List<NhanVien> listNV;
    private List<BangDanhSachChamCong> listCC;
    private final String FILEPB = "PB.TXT", FILENV = "NV.TXT", FILECC = "CHAMCONG.TXT";

    public FormChamCong() {
        initComponents();

        String cols[] = {"Ten NV", "Ten phong", "So ngay lam"};
        model = new DefaultTableModel(cols, 0);

        listCC = new ArrayList<>();

        table.setModel(model);
        btnFalse();
    }

    private void initCbData() {
        listPB = new ArrayList<>();
        listNV = new ArrayList<>();
        try {
            listPB = IOFile.readFile(FILEPB);
            listNV = IOFile.readFile(FILENV);
            if (listPB.isEmpty() || listNV.isEmpty()) {
                throw new InputMismatchException();
            }
            initItemData(cbPB, listPB);
            initItemData(cbNV, listNV);
            btnTrue();
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        }

    }

    private <T> void initItemData(JComboBox cb, List<T> list) {
        cb.removeAllItems();
        for (T t : list) {
            if (t instanceof NhanVien) {
                cb.addItem(((NhanVien) t).getMaNhanVien());
            } else if (t instanceof PhongBan) {
                cb.addItem(((PhongBan) t).getMaPhongBan());
            }
        }
    }

    private void btnTrue() {
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);

    }

    private void btnFalse() {
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);

    }

    private void clearData() {
        tfNgay.setText("");
    }

    private String formatInputString(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    private boolean canAddDataToList(int maNV) {
        for (BangDanhSachChamCong cc : listCC) {
            if (cc.getNhanVien().getMaNhanVien() == maNV) {
                return false;
            }
        }
        return true;
    }

    private <T> T findByMa(int ma, List<T> list) {
        for (T t : list) {
            if (t instanceof NhanVien) {
                if(((NhanVien) t).getMaNhanVien() == ma)
                    return t;
            } else if (t instanceof PhongBan) {
                if(((PhongBan) t).getMaPhongBan() == ma)
                    return t;
            }
        }
        return null;
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNgay = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        cbPB = new javax.swing.JComboBox<>();
        cbNV = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel1.setText("Ma NV");

        jLabel2.setText("Ma PB");

        jLabel4.setText("So ngay lam");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(95, 95, 95))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNgay)
                    .addComponent(cbPB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(20, 20, 20))
        );

        jLabel3.setText("sap xep theo:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ten nhan vien");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Phong ban");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnThem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jRadioButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButton2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        clearData();
        initCbData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        int soNgay = 0;
        int maNV = 0;
        int maPB = 0;
        boolean isOk = true;
        try {
            try {
                maNV = (int) cbNV.getSelectedItem();
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Khong co du lieu Nhan Vien");
                isOk = false;
            }
            try {
                maPB = (int) cbPB.getSelectedItem();

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Khong co du lieu Phong ban");
                isOk = false;

            }
            if (!canAddDataToList(maNV)) {
                throw new IOException();
            }

            try {
                String ngayString = formatInputString(tfNgay.getText());
                if (ngayString.length() == 0) {
                    throw new IOException();
                }
                soNgay = Integer.parseInt(ngayString);
                if (soNgay <= 0 || soNgay > 31) {
                    throw new InputMismatchException();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "So ngay khong de trong");
                isOk = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "So ngay chi nhap so");
                isOk = false;
            } catch (InputMismatchException e) {
                JOptionPane.showMessageDialog(null, "So ngay trong khoang tu 1 den 31");
                isOk = false;
            }

            if (isOk) {
                try{
                    NhanVien nhanVien = findByMa(maNV, listNV);
                    PhongBan phong = findByMa(maPB, listPB);
                    BangDanhSachChamCong chamCong = new BangDanhSachChamCong(nhanVien, phong, soNgay);
                    addToList(chamCong, listCC);
                    clearData();
                    btnFalse();
                    IOFile.writeFile(FILECC, listCC);
                } catch(NullPointerException e){
                    JOptionPane.showConfirmDialog(null, "Khong tim thay du lieu");
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Nhan vien da tham gia trong phong ban khac");

        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        clearData();
        btnFalse();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        try{
            listCC = IOFile.readFile(FILECC);
            if(listCC.isEmpty())
                throw new InputMismatchException();
            Collections.sort(listCC, (c1, c2) -> {
                return c1.getNhanVien().getHoTen().compareToIgnoreCase(c2.getNhanVien().getHoTen());
            });
            showData(listCC, model);
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        try{
            listCC = IOFile.readFile(FILECC);
            if(listCC.isEmpty())
                throw new InputMismatchException();
            Collections.sort(listCC, (c1, c2) -> {
                return c1.getPhongBan().getTenPhong().compareToIgnoreCase(c2.getPhongBan().getTenPhong());
            });
            showData(listCC, model);
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JComboBox<String> cbPB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfNgay;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addToList(T t, List<T> ls) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for (T t : ls) {
            if (t instanceof BangDanhSachChamCong) {
                md.addRow(((BangDanhSachChamCong) t).toObjects());
            }
        }
    }
}
