package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangTinhCong;
import model.KieuBaiViet;
import model.PhongVien;

/**
 *
 * @author whiwf
 */
public class FormTinhCong extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormTinhCong
     */
    private DefaultTableModel model;
    private List<PhongVien> listPV;
    private List<KieuBaiViet> listKB;
    private List<BangTinhCong> listTC;
    private final String FILEPV = "PV.TXT", FILEKB = "KB.TXT", FILETC = "TINHCONG.TXT";
    private final int COUNT = 5;

    public FormTinhCong() {
        initComponents();
        String colsString[] = {"Ten PV", "Ten kieu bai", "So luong"};
        model = new DefaultTableModel(colsString, 0);
        table.setModel(model);

        btnFalse();
        
        listTC = new ArrayList<>();
    }

    private void initCbData() {
        
        listPV = new ArrayList<>();
        listKB = new ArrayList<>();
        try {
            listPV = IOFile.readFile(FILEPV);
            listKB = IOFile.readFile(FILEKB);
            
            if (listPV.isEmpty() || listKB.isEmpty()) {
                throw new InputMismatchException();
            }
            initItemToCb(cbKB, listKB);
            initItemToCb(cbPV, listPV);
            btnTrue();
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        }
    }

    private <T> void initItemToCb(JComboBox cb, List<T> list) {
        cb.removeAllItems();
        for (T t : list) {
            if (t instanceof PhongVien) {
                cb.addItem(((PhongVien) t).formatMa());
            } else if (t instanceof KieuBaiViet) {
                cb.addItem(((KieuBaiViet) t).formatMa());
            }
        }
    }

    private void clearData() {
        tfSo.setText("");
    }

    private void btnTrue() {
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }

    private void btnFalse() {
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }

    private String formatInputString(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    private boolean isExistData(int maPV, int maKB) {
        for (BangTinhCong tc : listTC) {
            if (tc.getPhongVien().getMaPhongVien() == maPV && tc.getKieuBaiViet().getMaKieuBai() == maKB) {
                return true;
            }
        }
        return false;
    }

    private boolean isOverData(int maPV) {
        int so = 0;
        for (BangTinhCong tc : listTC) {
            if (tc.getPhongVien().getMaPhongVien() == maPV) {
                so++;
            }
        }
        return so >= COUNT;
    }

    private <T> T findByMa(int ma, List<T> list) {
        for (T t : list) {
            if (t instanceof PhongVien) {
                if (((PhongVien) t).getMaPhongVien() == ma) {
                    return t;
                }
            } else if (t instanceof KieuBaiViet) {
                if (((KieuBaiViet) t).getMaKieuBai() == ma) {
                    return t;
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        tfSo = new javax.swing.JTextField();
        cbPV = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbKB = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel2.setText("So luong");

        jLabel3.setText("Ma PV");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel4.setText("Ma KB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(cbKB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPV, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnLuu))
                .addContainerGap())
        );

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Sap xep theo:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ten PV");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("So luong bai");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(btnThem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButton2)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        int maPV = Integer.parseInt((String) cbPV.getSelectedItem());
        int maKB = Integer.parseInt((String) cbKB.getSelectedItem());

        int soLuong = 0;
        boolean isOk = true;
        try {
            if (isExistData(maPV, maKB)) {
                throw new IOException();
            }
            if (isOverData(maPV)) {
                throw new InputMismatchException();
            }
            PhongVien pv = findByMa(maPV, listPV);
            KieuBaiViet kieuBaiViet = findByMa(maKB, listKB);
            try {
                String so = formatInputString(tfSo.getText());
                if (so.length() == 0) {
                    throw new InputMismatchException();
                }
                soLuong = Integer.parseInt(so);
                if(soLuong <= 0){
                    throw new IOException();
                }
            } catch (InputMismatchException e) {
                JOptionPane.showMessageDialog(null, "so luong khong de trong");
                isOk = false;
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "so luong phai lon hon 0");
                isOk = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "so luong sai dinh dang");
                isOk = false;
            }
            if(isOk){
                BangTinhCong tc = new BangTinhCong(pv, kieuBaiViet, soLuong);
                addToList(listTC, tc);
                IOFile.writeFile(FILETC, listTC);
                btnFalse();
                clearData();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "du lieu da ton tai");
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "phong vien da viet qua " + COUNT + " kieu bai");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "khong co du lieu");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        btnFalse();
        clearData();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        initCbData();
        clearData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        try{
            listTC = IOFile.readFile(FILETC);
            if(listTC.isEmpty())
                throw new IOException();
            Collections.sort(listTC, (t1, t2) -> {
                return t1.getPhongVien().getHoTen().compareToIgnoreCase(t2.getPhongVien().getHoTen());
            });
            showData(listTC, model);
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try{
            listTC = IOFile.readFile(FILETC);
            if(listTC.isEmpty())
                throw new IOException();
            Collections.sort(listTC, (t1, t2) -> {
                int so1 = t1.getSoLuong();
                int so2 = t2.getSoLuong();
                return so2 > so1 ? 1 : so2 < so1 ? -1 : 0;
            });
            showData(listTC, model);
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKB;
    private javax.swing.JComboBox<String> cbPV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfSo;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addToList(List<T> ls, T t) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for (T t : ls) {
            if (t instanceof BangTinhCong) {
                md.addRow(((BangTinhCong) t).toObjects());
            }
        }
    }
}
