package view;

import io.IOFile;
import java.io.IOError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DanhSachBanHang;
import model.MatHang;
import model.NhanVienBanHang;

/**
 *
 * @author whiwf
 */
public class FormBanHang extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormBanHang
     */
    private DefaultTableModel model;
    private List<MatHang> listMH;
    private List<NhanVienBanHang> listNV;
    private List<DanhSachBanHang> listBH;

    private final String fileMH = "MH.TXT", fileNV = "NV.TXT", fileBH = "QLBH.TXT";

    public FormBanHang() {
        initComponents();
        String cols[] = {"Ten NV", "Ten MH", "So luong"};
        model = new DefaultTableModel(cols, 0);
        table.setModel(model);

        listBH = new ArrayList<>();

        btnFalse();
    }

    private void initCbData() {
        listMH = new ArrayList<>();
        listMH = IOFile.readFile(fileMH);

        listNV = new ArrayList<>();
        listNV = IOFile.readFile(fileNV);

        try {
            if (listNV.isEmpty() || listMH.isEmpty()) {
                throw new IOException();
            }
            initItemToCb(cbNV, listNV);
            initItemToCb(cbMH, listMH);
            btnTrue();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Du lieu con trong");
        }
    }

    private <T> void initItemToCb(JComboBox cbBox, List<T> ls) {
        cbBox.removeAllItems();
        for (T t : ls) {
            if (t instanceof MatHang) {
                cbBox.addItem(((MatHang) t).formatMa());
            } else if (t instanceof NhanVienBanHang) {
                cbBox.addItem(((NhanVienBanHang) t).formatMa());
            }
        }
    }

    private void btnTrue() {
        btnHuy.setEnabled(true);
        btnLuu.setEnabled(true);
    }

    private void btnFalse() {
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
    }

    private void clearData() {
        tfSo.setText("");
    }

    private boolean canAddToList(int maNV, int maMH) {
        for (DanhSachBanHang bh : listBH) {
            if (bh.getNhanVienBanHang().getMa() == maNV && bh.getMatHang().getMa() == maMH) {
                return false;
            }
        }
        return true;
    }

    private <T> T findByMa(int ma, List<T> ls) {
        for (T t : ls) {
            if (t instanceof MatHang) {
                if (((MatHang) t).getMa() == ma) {
                    return t;
                }
            } else if (t instanceof NhanVienBanHang) {
                if (((NhanVienBanHang) t).getMa() == ma) {
                    return t;
                }
            }
        }
        return null;
    }

    private String stringInputFormat(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        cbNV = new javax.swing.JComboBox<>();
        tfSo = new javax.swing.JTextField();
        cbMH = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbtnTenNV = new javax.swing.JRadioButton();
        rbtnTenMH = new javax.swing.JRadioButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel2.setText("Ma NV");

        jLabel3.setText("So luong");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel5.setText("Ma MH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMH, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbNV, 0, 234, Short.MAX_VALUE)
                        .addComponent(tfSo)))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(28, 28, 28))
        );

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Sap xep theo");

        buttonGroup1.add(rbtnTenNV);
        rbtnTenNV.setText("Ten NV");
        rbtnTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTenNVActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTenMH);
        rbtnTenMH.setText("Ten MH");
        rbtnTenMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTenMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(btnThem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(rbtnTenNV)
                        .addGap(58, 58, 58)
                        .addComponent(rbtnTenMH)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtnTenNV)
                    .addComponent(rbtnTenMH))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        int maNV = Integer.parseInt((String) cbNV.getSelectedItem());
        int maMH = Integer.parseInt((String) cbMH.getSelectedItem());
        int soLuong = 0;
        boolean isOk = true;
        try {
            if (!canAddToList(maNV, maMH)) {
                throw new IOException();
            }
            try {
                String so = stringInputFormat(tfSo.getText());
                if (so.length() == 0) {
                    throw new IOException();
                }
                soLuong = Integer.parseInt(so);
                if (soLuong <= 0) {
                    throw new NumberFormatException();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "So luong khong de trong");
                isOk = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "So luong sai dinh dang");
                isOk = false;
            }
            if (isOk) {
                NhanVienBanHang nv = findByMa(maNV, listNV);
                MatHang mh = findByMa(maMH, listMH);
                DanhSachBanHang bh = new DanhSachBanHang(nv, mh, soLuong);
                addToList(listBH, bh);
                IOFile.writeFile(fileBH, listBH);
                btnFalse();
                clearData();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Du lieu da ton tai");
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        btnFalse();
        clearData();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        clearData();
        initCbData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void rbtnTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTenNVActionPerformed
        try {
            listBH = IOFile.readFile(fileBH);
            if (listBH.isEmpty()) {
                throw new InputMismatchException();
            }
            Collections.sort(listBH, (b1, b2) -> {
                return b1.getNhanVienBanHang().getTen().compareToIgnoreCase(b2.getNhanVienBanHang().getTen());
            });
            showData(listBH, model);
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_rbtnTenNVActionPerformed

    private void rbtnTenMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTenMHActionPerformed
        try {
            listBH = IOFile.readFile(fileBH);
            if(listBH.isEmpty())
                throw new InputMismatchException();
            Collections.sort(listBH, (b1, b2) -> {
                return b1.getMatHang().getTen().compareToIgnoreCase(b2.getMatHang().getTen());
            });
            showData(listBH, model);
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_rbtnTenMHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMH;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnTenMH;
    private javax.swing.JRadioButton rbtnTenNV;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfSo;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addToList(List<T> ls, T t) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for (T t : ls) {
            if (t instanceof DanhSachBanHang) {
                md.addRow(((DanhSachBanHang) t).toObjects());
            }
        }
    }
}
