package view;

import io.IOFile;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JOptionPane;
import model.DanhSachBanHang;

/**
 *
 * @author whiwf
 */
public class FormTinhCong extends javax.swing.JPanel {

    /**
     * Creates new form FormTinhCong
     */
    private final String title = "Ten NV\tTenMH\tSo luong\n";
    private final String file = "QLBH.TXT";
    private final float HESO = (float) 0.02;
    private List<DanhSachBanHang> list;

    public FormTinhCong() {
        initComponents();
        clearData();

    }

    private void clearData() {
        jTextArea1.setText("");
        jTextField1.setText("");
    }

    private void initDataToCb() {
        cbNV.removeAllItems();
        HashSet<String> set = new HashSet<>();
        for (DanhSachBanHang bh : list) {
            set.add(bh.getNhanVienBanHang().formatMa());
        }
        for (String item : set) {
            cbNV.addItem(item);
        }
    }

    private String findDataByMa(int ma) {
        String text = "" + title;
        for (DanhSachBanHang bh : list) {
            if (bh.getNhanVienBanHang().getMa() == ma) {
                text += bh;
            }
        }
        return text;
    }

    private float tinhLuong(int ma){
        float tong = 0;
        for(DanhSachBanHang bh : list){
            if(bh.getNhanVienBanHang().getMa() == ma){
                tong += 1.0*bh.getSo()*(bh.getMatHang().getGiaBan() - bh.getMatHang().getGiaMua());
            }
        }
        return tong*HESO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cbNV = new javax.swing.JComboBox<>();
        btnTao = new javax.swing.JButton();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Tinh cong");

        jLabel2.setText("Tong luong");

        jTextField1.setEditable(false);

        cbNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNVActionPerformed(evt);
            }
        });

        btnTao.setText("Tao");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jTextField1))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTao)
                        .addGap(186, 186, 186))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTao)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        list = new ArrayList<>();
        try {
            list = IOFile.readFile(file);
            if (list.isEmpty()) {
                throw new InputMismatchException();
            }
            initDataToCb();
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Du lieu con trong");
        }
    }//GEN-LAST:event_btnTaoActionPerformed

    private void cbNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNVActionPerformed
        try {
            clearData();
            int ma = Integer.parseInt((String) cbNV.getSelectedItem());
            jTextArea1.setText(findDataByMa(ma));
            jTextField1.setText(tinhLuong(ma) + "");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Du lieu con trong");
        }
    }//GEN-LAST:event_cbNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTao;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
