package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanHang;
import model.KhachHang;
import model.MatHang;

/**
 *
 * @author whiwf
 */
public class FrBanHang extends javax.swing.JPanel implements View {

    /**
     * Creates new form FrBanHang
     */
    private DefaultTableModel model;
    private List<BanHang> listBH;
    private List<MatHang> listMH;
    private List<KhachHang> listKH;
    private Map<MatHang, Integer> dsMuaHang;
    private String fileBH = "QLBH.TXT", fileMH = "MH.TXT", fileKH = "KH.TXT";

    private final int MAXNUMBERPERTIME = 10;

    public FrBanHang() {
        initComponents();
        String colShowTable[] = {"Ten KH", "Ten MH", "So luong"};
        model = new DefaultTableModel(colShowTable, 0);
        jTable2.setModel(model);

        listBH = new ArrayList<>();
        dsMuaHang = new HashMap<>();

        btnFalse();
    }

    private void initDataCbMH() {
        listMH = new ArrayList<>();
        cbMH.removeAllItems();
        listMH = IOFile.readFromFile(fileMH);
        if (listMH.size() > 0) {
            for (MatHang h : listMH) {
                cbMH.addItem(h.formatMa());
            }
        }
    }

    private void initDataCbKH() {
        listKH = new ArrayList<>();
        cbKH.removeAllItems();
        listKH = IOFile.readFromFile(fileKH);
        if (listMH.size() > 0) {
            for (KhachHang h : listKH) {
                cbKH.addItem(h.formatMa());
            }
        }
    }

    private void btnTrue() {
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jTextField1.setEditable(true);
    }

    private void btnFalse() {
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jTextField1.setEditable(false);
    }

    private void clearData() {
        jTextField1.setText("");
    }

    private KhachHang findKHByMa(int ma) {
        for (KhachHang k : listKH) {
            if (k.getMa() == ma) {
                return k;
            }
        }
        return null;
    }

    private MatHang findMHByMa(int ma) {
        for (MatHang h : listMH) {
            if (h.getMa() == ma) {
                return h;
            }
        }
        return null;
    }

    private boolean isOverPerTime(int maKH) {
        int dem = 0;
        for (BanHang bh : listBH) {
            int ma = bh.getKhachHang().getMa();
            if (ma == maKH) {
                dem++;
            }
        }
        return dem == MAXNUMBERPERTIME;
    }

    private boolean isExistData(int maKH, int maMH) {
        for (BanHang bh : listBH) {
            if (bh.getHang().getMa() == maMH && bh.getKhachHang().getMa() == maKH) {
                return true;
            }
        }
        return false;
    }

    private void sortByKH() {
        Collections.sort(listBH, (bh1, bh2) -> {
            return bh1.getKhachHang().getHoTen().compareToIgnoreCase(bh2.getKhachHang().getHoTen());
        });
        showData(listBH, model);
    }

    private void sortByMH() {
        Collections.sort(listBH, (bh1, bh2) -> {
            return bh1.getHang().getTen().compareToIgnoreCase(bh2.getHang().getTen());
        });
        showData(listBH, model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbKH = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbMH = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnKH = new javax.swing.JRadioButton();
        btnMH = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them Ban hang"));

        jLabel1.setText("Ma KH");

        jLabel2.setText("Ma MH");

        jButton2.setText("Luu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Huy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("So luong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMH, 0, 168, Short.MAX_VALUE)
                    .addComponent(cbKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Them");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnKH);
        btnKH.setText("Ten KH");

        buttonGroup1.add(btnMH);
        btnMH.setText("Ten MH");

        jLabel4.setText("Sap xep theo:");

        jButton4.setText("Xep");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnKH)
                        .addGap(18, 18, 18)
                        .addComponent(btnMH)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKH)
                    .addComponent(btnMH)
                    .addComponent(jLabel4)
                    .addComponent(jButton4))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        initDataCbMH();
        initDataCbKH();
        try {
            if (listKH.isEmpty() || listMH.isEmpty()) {
                throw new IOException();
            }
            btnTrue();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Khach hang hoac Mat hang khong ton tai");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        btnFalse();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int maKH = Integer.parseInt((String) cbKH.getSelectedItem());
        int maMH = Integer.parseInt((String) cbMH.getSelectedItem());
        int so = 0;
        boolean isOk = true;
        try {
            so = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "So luong sai dinh dang");
            isOk = false;
        }
        if (isOk) {
            KhachHang k = findKHByMa(maKH);
            MatHang h = findMHByMa(maMH);
            try {
                if (isExistData(maKH, maMH)) {
                    throw new IOException();
                }
                if (isOverPerTime(maKH)) {
                    throw new InputMismatchException();
                }
                BanHang ban = new BanHang(k, h, so);
                addTo(ban);
                clearData();
                btnFalse();
                IOFile.writeToFile(listBH, fileBH);
            } catch (InputMismatchException e) {
                JOptionPane.showMessageDialog(null, "Moi KH chi mua 10 loai MH");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "KH da mua loai MH nay");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (btnKH.isSelected()) {
            sortByKH();
        } else if (btnMH.isSelected()) {
            sortByMH();
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnKH;
    private javax.swing.JRadioButton btnMH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKH;
    private javax.swing.JComboBox<String> cbMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addTo(T t) {
        BanHang bh = (BanHang) t;
        listBH.add(bh);
        dsMuaHang.put(bh.getHang(), bh.getSo());
        showData(listBH, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : ls) {
            this.model.addRow(((BanHang) t).toObject());
        }
    }
}
