/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.LoaiVe;
import model.NguoiMuaVe;

/**
 *
 * @author whiwf
 */
public class FormHoaDon extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormHoaDon
     */
    private DefaultTableModel model;
    private List<LoaiVe> listVE;
    private List<NguoiMuaVe> listNM;
    private List<HoaDon> listHD;

    private final String FILEVE = "VE.TXT", FILENM = "NGUOIMUA.TXT", FILEHD = "HOADON.TXT";
    private final int SOLOAI = 3, SOVE = 10;

    public FormHoaDon() {
        initComponents();
        String cols[] = {"Ten nguoi mua", "Loai ve", "So luong"};
        model = new DefaultTableModel(cols, 0);
        table.setModel(model);

        listHD = new ArrayList<>();
        btnFalse();

    }

    private void initCbData() {
        listNM = new ArrayList<>();
        listVE = new ArrayList<>();
        try {
            listNM = IOFile.readFile(FILENM);
            listVE = IOFile.readFile(FILEVE);
            if (listNM.isEmpty() || listVE.isEmpty()) {
                throw new NullPointerException();
            }
            initItemToCb(cbNguoi, listNM);
            initItemToCb(cbVe, listVE);
            btnTrue();
            clearData();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        }
    }

    private <T> void initItemToCb(JComboBox cb, List<T> list) {
        cb.removeAllItems();
        for (T t : list) {
            if (t instanceof NguoiMuaVe) {
                cb.addItem(((NguoiMuaVe) t).getMaNguoiMua());
            } else if (t instanceof LoaiVe) {
                cb.addItem(((LoaiVe) t).getMaVe());
            }
        }
    }

    private void clearData() {
        tfSo.setText("");
    }

    private void btnTrue() {
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }

    private void btnFalse() {
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }

    private String formatInputString(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    private boolean isExistData(int maNM, int maVe) {
        for (HoaDon hd : listHD) {
            if (hd.getNguoiMuaVe().getMaNguoiMua() == maNM && hd.getVe().getMaVe() == maVe) {
                return true;
            }
        }
        return false;
    }

    private boolean isOverType(int maNM) {
        int dem = 0;
        for (HoaDon hd : listHD) {
            if (hd.getNguoiMuaVe().getMaNguoiMua() == maNM) {
                dem++;
            }
        }
        return dem >= SOLOAI;
    }

    private boolean isOverTiketsNumber(int so) {
        return so > SOVE;
    }

    private <T> T findByMa(List<T> list, int ma) {
        for (T t : list) {
            if (t instanceof NguoiMuaVe) {
                if (((NguoiMuaVe) t).getMaNguoiMua() == ma) {
                    return t;
                }
            } else if (t instanceof LoaiVe) {
                if (((LoaiVe) t).getMaVe() == ma) {
                    return t;
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSo = new javax.swing.JTextField();
        cbNguoi = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbVe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel2.setText("So luong");

        jLabel3.setText("Ma nguoi mua");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel4.setText("Ma loai ve");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSo)
                    .addComponent(cbNguoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbVe, 0, 295, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(24, 24, 24))
        );

        jLabel1.setText("Sap xep theo:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ten nguoi mua");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("So luong ve");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(btnThem))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(49, 49, 49)
                        .addComponent(jRadioButton2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        initCbData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String soLuong = "";
        int maNM = 0, maVe = 0;
        int so = 0;
        boolean isOk = true;

        try {
            maNM = (int) cbNguoi.getSelectedItem();
            maVe = (int) cbVe.getSelectedItem();
            if (isExistData(maNM, maVe)) {
                throw new IOException();
            }
            if (isOverType(maNM)) {
                throw new InputMismatchException();
            }
            try {
                soLuong = formatInputString(tfSo.getText());
                if (soLuong.length() == 0) {
                    throw new IOException();
                }
                so = Integer.parseInt(soLuong);
                if (so <= 0) {
                    throw new InputMismatchException();
                }
                if (isOverTiketsNumber(so)) {
                    throw new IllegalAccessException();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "so luong khong de trong");
                isOk = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "so luong phai la so");
                isOk = false;

            } catch (InputMismatchException e) {
                JOptionPane.showMessageDialog(null, "so luong phai lon hon 0");
                isOk = false;

            } catch (IllegalAccessException e) {
                JOptionPane.showMessageDialog(null, "so luong da vuot qua " + SOVE + "/lan mua");
                isOk = false;

            }
            if (isOk) {
                NguoiMuaVe nguoi = findByMa(listNM, maNM);
                LoaiVe ve = findByMa(listVE, maVe);
                HoaDon h = new HoaDon(nguoi, ve, so);
                addToList(h, listHD);
                clearData();
                IOFile.writeFile(FILEHD, listHD);
                btnFalse();
            }  
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Nguoi nay da mua ve loai nay");

        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Nguoi nay da mua ve qua " + SOLOAI + " loai ve");

        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnFalse();
        clearData();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        try{
            listHD = IOFile.readFile(FILEHD);
            if(listHD.isEmpty())
                throw new IOException();
            Collections.sort(listHD, (h1, h2) -> {
                return h1.getNguoiMuaVe().getHoTen().compareToIgnoreCase(h2.getNguoiMuaVe().getHoTen());
            });
            showData(listHD, model);
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        try{
            listHD = IOFile.readFile(FILEHD);
            if(listHD.isEmpty())
                throw new IOException();
            Collections.sort(listHD, (h1, h2) -> {
                return h1.getSoLuong() > h2.getSoLuong() ? -1 : h1.getSoLuong() < h2.getSoLuong() ? 1 : 0;
            });
            showData(listHD, model);
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbNguoi;
    private javax.swing.JComboBox<String> cbVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfSo;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addToList(T t, List<T> ls) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for(T t : ls){
            if(t instanceof HoaDon){
                md.addRow(((HoaDon) t).toObjects());
            }
        }
    }
}
