package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDanhSachChamCong;
import model.CongNhan;
import model.XuongSanXuat;

/**
 *
 * @author whiwf
 */
public class FormChamCong extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormChamCong
     */
    private DefaultTableModel model;
    private List<BangDanhSachChamCong> listCC;
    private List<XuongSanXuat> listXSX;
    private List<CongNhan> listCN;
    private final String FILECN = "CN.TXT", FILEXSX = "XSX.TXT", FILECC = "QLCN.TXT";
    private final int TIME = 30;

    public FormChamCong() {
        initComponents();
        String colsString[] = {"Ten CN", "Ten xuong", "Ngay"};
        model = new DefaultTableModel(colsString, 0);
        table.setModel(model);

        listCC = new ArrayList<>();

        btnFalse();
    }

    private void initCbData() {
        listCN = new ArrayList<>();
        listCN = IOFile.readFile(FILECN);

        listXSX = new ArrayList<>();
        listXSX = IOFile.readFile(FILEXSX);

        try {
            if (listCN.isEmpty() || listXSX.isEmpty()) {
                throw new InputMismatchException();
            }
            initItemToCb(listCN, cbCN);
            initItemToCb(listXSX, cbXuong);
            btnTrue();
            clearData();
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Du lieu khong ton tai");
        }
    }

    private <T> void initItemToCb(List<T> list, JComboBox cb) {
        cb.removeAllItems();
        for (T t : list) {
            if (t instanceof CongNhan) {
                cb.addItem(((CongNhan) t).formatMa());
            } else if (t instanceof XuongSanXuat) {
                cb.addItem(((XuongSanXuat) t).formatMa());
            }
        }
    }

    private void clearData() {
        tfSo.setText("");
    }

    private void btnTrue() {
        btnHuy.setEnabled(true);
        btnLuu.setEnabled(true);
    }

    private void btnFalse() {
        btnHuy.setEnabled(false);
        btnLuu.setEnabled(false);
    }

    private void rTrue(){
        rCN.setEnabled(true);
        rXuong.setEnabled(true);
    }
    
    private void rFalse(){
        rCN.setEnabled(false);
        rXuong.setEnabled(false);
    }
    
    private String stringInputFormat(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    private boolean isOver(int ma, int curNgay) {
        int ngay = 0;
        for (BangDanhSachChamCong cham : listCC) {
            if (cham.getCongNhan().getMa() == ma) {
                ngay += cham.getNgay();
            }
        }
        return ngay + curNgay > TIME;
    }

    private <T> T findByMa(int ma, List<T> list) {
        for (T t : list) {
            if (t instanceof CongNhan) {
                if (((CongNhan) t).getMa() == ma) {
                    return t;
                }
            } else if (t instanceof XuongSanXuat) {
                if (((XuongSanXuat) t).getMa() == ma) {
                    return t;
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfSo = new javax.swing.JTextField();
        cbCN = new javax.swing.JComboBox<>();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbXuong = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rCN = new javax.swing.JRadioButton();
        rXuong = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel3.setText("So ngay");

        jLabel4.setText("Ma CN");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel5.setText("Ma Xuong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(cbXuong, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbXuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Sap xep");

        buttonGroup1.add(rCN);
        rCN.setText("Ten CN");
        rCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCNActionPerformed(evt);
            }
        });

        buttonGroup1.add(rXuong);
        rXuong.setText("Ten Xuong");
        rXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rXuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(btnThem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(rCN)
                        .addGap(70, 70, 70)
                        .addComponent(rXuong)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rCN)
                    .addComponent(rXuong))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        int maCN = Integer.parseInt((String) cbCN.getSelectedItem());
        int maXuong = Integer.parseInt((String) cbXuong.getSelectedItem());
        int ngay = 0;
        boolean isOk = true;
        try {
            String ngayLam = stringInputFormat(tfSo.getText());
            if (ngayLam.length() == 0) {
                throw new IOException();
            }
            ngay = Integer.parseInt(ngayLam);
            if (ngay <= 0 || ngay > 30) {
                throw new NumberFormatException();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "so ngay khong de trong");
            isOk = false;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "so ngay sai dinh dang");
            isOk = false;
        }
        if (isOk) {
            try {
                if (isOver(maCN, ngay)) {
                    throw new InputMismatchException();
                }
                XuongSanXuat xuong = findByMa(maXuong, listXSX);
                CongNhan congNhan = findByMa(maCN, listCN);
                BangDanhSachChamCong cc = new BangDanhSachChamCong(congNhan, xuong, ngay);
                addToList(listCC, cc);
                IOFile.writeFile(FILECC, listCC);
                clearData();
                btnFalse();
            } catch (InputMismatchException e) {
                JOptionPane.showMessageDialog(null, "So ngay da vuot qua cho phep");
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        clearData();
        btnFalse();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        initCbData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void rCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCNActionPerformed
        try {
            listCC = IOFile.readFile(FILECC);
            if (listCC.isEmpty()) {
                throw new InputMismatchException();
            }
            Collections.sort(listCC, (c1, c2) -> {
                return c1.getCongNhan().getTen().compareToIgnoreCase(c2.getCongNhan().getTen());
            });
            showData(listCC, model);
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_rCNActionPerformed

    private void rXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rXuongActionPerformed

        try {
            listCC = IOFile.readFile(FILECC);
            Collections.sort(listCC, (c1, c2) -> {
                return c1.getXuong().getTen().compareToIgnoreCase(c2.getXuong().getTen());
            });
            showData(listCC, model);
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_rXuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCN;
    private javax.swing.JComboBox<String> cbXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rCN;
    private javax.swing.JRadioButton rXuong;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfSo;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void addToList(List<T> ls, T t) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for (T t : ls) {
            if (t instanceof BangDanhSachChamCong) {
                md.addRow(((BangDanhSachChamCong) t).toObjects());
            }
        }
    }
}
