package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import model.BangDanhSachChamCong;

/**
 *
 * @author whiwf
 */
public class FormThongKe extends javax.swing.JPanel {

    /**
     * Creates new form FormThongKe
     */
    private List<BangDanhSachChamCong> list;
    private final String TITLE = "Ten NV\tTen xuong\tSo ngay\n", FILE = "QLCN.TXT";

    public FormThongKe() {
        initComponents();
        list = new ArrayList<>();
        taThongKe.setText("");
        tfLuong.setText("");
    }

    private void initCbData() {
        cbNV.removeAllItems();
        HashSet<String> ma = new HashSet<>();
        for (BangDanhSachChamCong c : list) {
            ma.add(c.getCongNhan().formatMa());
        }
        for (String item : ma) {
            cbNV.addItem(item);
        }
    }

    private void showData(int ma) {

        String text = "" + TITLE;
        for (BangDanhSachChamCong c : list) {
            if (c.getCongNhan().getMa() == ma) {
                text += c;
            }
        }
        taThongKe.setText(text);
    }

    private float calcThuNhap(int ma) {
        float luong = 0;
        for (BangDanhSachChamCong c : list) {
            if (c.getCongNhan().getMa() == ma) {
                luong += 1.0 * 450000 * c.getCongNhan().getBac() * c.getXuong().getHeSo() * (1.0 * c.getNgay() / 22);
            }
        }
        return luong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taThongKe = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfLuong = new javax.swing.JTextField();
        cbNV = new javax.swing.JComboBox<>();
        btnTao = new javax.swing.JButton();

        taThongKe.setEditable(false);
        taThongKe.setColumns(20);
        taThongKe.setRows(5);
        jScrollPane1.setViewportView(taThongKe);

        jLabel1.setText("Luong");

        tfLuong.setEditable(false);

        cbNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNVActionPerformed(evt);
            }
        });

        btnTao.setText("Tao");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(tfLuong))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnTao)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(cbNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnTao)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        try {
            list = IOFile.readFile(FILE);
            if (list.isEmpty()) {
                throw new IOException();
            }
            initCbData();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        }
    }//GEN-LAST:event_btnTaoActionPerformed

    private void cbNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNVActionPerformed
        int ma = 0;
        try {
            ma = Integer.parseInt((String) cbNV.getSelectedItem());
            showData(ma);
            tfLuong.setText(calcThuNhap(ma) + "");
        } catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_cbNVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTao;
    private javax.swing.JComboBox<String> cbNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taThongKe;
    private javax.swing.JTextField tfLuong;
    // End of variables declaration//GEN-END:variables
}
