package view;

import io.IOFile;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangSapXep;
import model.KhachHang;
import model.OTo;

/**
 *
 * @author whiwf
 */
public class FormSapXep extends javax.swing.JPanel implements ViewInterface {

    /**
     * Creates new form FormSapXep
     */
    private DefaultTableModel model;
    private List<BangSapXep> listSX;
    private List<KhachHang> listKH;
    private List<OTo> listOTO;
    private final String FILESX = "BANGSX.TXT", FILEKH = "KH.TXT", FILEOTO = "OTO.TXT";

    public FormSapXep() {
        initComponents();
        String cols[] = {"Ten KH", "Kieu xe", "So ngay", "So xe can thue"};
        model = new DefaultTableModel(cols, 0);
        table.setModel(model);

        listSX = new ArrayList<>();
        btnFalse();
    }

    private void initCbData() {
        cbKH.removeAllItems();

        listKH = new ArrayList<>();
        listOTO = new ArrayList<>();
        try {
            listKH = IOFile.readFile(FILEKH);
            listOTO = IOFile.readFile(FILEOTO);
            if (listKH.isEmpty() || listOTO.isEmpty()) {
                throw new InputMismatchException();
            }
            for (KhachHang k : listKH) {
                cbKH.addItem(k.formatMa());
            }
            btnTrue();
        } catch (InputMismatchException e) {
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
        }
    }

    private void btnTrue() {
        btnLuu.setEnabled(true);
        btnHuy.setEnabled(true);
    }

    private void btnFalse() {
        btnLuu.setEnabled(false);
        btnHuy.setEnabled(false);
    }

    private KhachHang findKHByMa(int ma) {
        for (KhachHang k : listKH) {
            if (k.getMa() == ma) {
                return k;
            }
        }
        return null;
    }

    private OTo findOToByRequire(String xeMuonThue) {
        for (OTo xe : listOTO) {
            if (xe.getKieuXe().equalsIgnoreCase(xeMuonThue)) {
                return xe;
            }
        }
        return null;
    }

    private boolean isEnoughCarToRent(OTo xe, String require, int so) {
        int soXe = 0;
        for (BangSapXep xep : listSX) {
            if (xep.getoTo().getKieuXe().equalsIgnoreCase(require)) {
                soXe += xep.getKhachHang().getSoXe();
            }
        }
        return soXe + so <= xe.getSoXe();
    }

    private String formatStringInput(String s) {
        return s.replaceAll("\\s+", " ").trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbKH = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfNgay = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Them"));

        jLabel1.setText("Ma KH");

        jLabel2.setText("So ngay");

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Huy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbKH, 0, 248, Short.MAX_VALUE)
                    .addComponent(tfNgay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnLuu)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel3.setText("Sap xe theo:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Kieu xe");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("So xe can thue");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(btnThem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButton1)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButton2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        initCbData();
        clearData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        int maKH = Integer.parseInt((String) cbKH.getSelectedItem());
        int soNgayThue = 0;
        boolean isOk = true;

        try {
            KhachHang khach = findKHByMa(maKH);
            OTo xe = findOToByRequire(khach.getLoaiXeMuonThue());
            if (!isEnoughCarToRent(xe, xe.getKieuXe(), khach.getSoXe())) {
                throw new IOException();
            }
            try {
                String soNgay = formatStringInput(tfNgay.getText());
                if (soNgay.length() == 0) {
                    throw new IOException();
                }
                soNgayThue = Integer.parseInt(soNgay);
                if (soNgayThue <= 0) {
                    throw new NumberFormatException();
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "So ngay khong de trong");
                isOk = false;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "So ngay sai dinh dang");
                isOk = false;
            }
            if (isOk) {
                BangSapXep xep = new BangSapXep(khach, xe, soNgayThue);
                addToList(listSX, xep);
                IOFile.writeFile(FILESX, listSX);
                clearData();
                btnFalse();
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Khong co loai xe mong muon");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Khong co du xe cho thue");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        clearData();
        btnFalse();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        try{
            listSX = IOFile.readFile(FILESX);
            if(listSX.isEmpty())
                throw new InputMismatchException();
            Collections.sort(listSX, (x1, x2) -> {
                return x1.getoTo().getKieuXe().compareToIgnoreCase(x2.getoTo().getKieuXe());
            });
            showData(listSX, model);
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try{
            listSX = IOFile.readFile(FILESX);
            if(listSX.isEmpty())
                throw new InputMismatchException();
            Collections.sort(listSX, (x1, x2) ->{
                return x1.getKhachHang().getSoXe() < x2.getKhachHang().getSoXe() ? -1 
                        : x1.getKhachHang().getSoXe() > x2.getKhachHang().getSoXe() ? 1 : 0;
            });
            showData(listSX, model);
        } catch(InputMismatchException e){
            JOptionPane.showMessageDialog(null, "Khong co du lieu");
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfNgay;
    // End of variables declaration//GEN-END:variables

    private void clearData() {
        tfNgay.setText("");
    }

    @Override
    public <T> void addToList(List<T> ls, T t) {
        ls.add(t);
        showData(ls, model);
    }

    @Override
    public <T> void showData(List<T> ls, DefaultTableModel md) {
        md.setRowCount(0);
        for (T t : ls) {
            if (t instanceof BangSapXep) {
                md.addRow(((BangSapXep) t).toObjects());
            }
        }
    }
}
